
import { Roboto } from "next/font/google"; 
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { PlaygroundProvider } from "@/context/playgroundProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <PlaygroundProvider>
      <html lang="en">
        <head>
          <title>CodingWizad | Collaborate in Real-Time, Build Together</title>
          <link
            href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
            rel="stylesheet"
          />
          <link
            href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Roboto:wght@400;700&display=swap"
            rel="stylesheet"
          />
          
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          />
          <link rel="icon" href="/icon.svg" type="image/png" />
        </head>
        <body
          className={`${roboto.className} antialiased`}
        >
          <Toaster />
          {children}
        </body>
      </html>
    </PlaygroundProvider>
  );
}
